apiVersion: v2
appVersion: "v1.0.1"
home: https://github.com/enzyme-health/k8s-as-helm
description: Helm Chart representing a single Job Kubernetes API object
name: job
version: 1.0.1
icon: https://enzyme-health.github.io/k8s-as-helm/icon.png
dependencies:
- name: lib-k8s-as-helm
  version: 1.1.0
  repository: file://../lib-k8s-as-helm
maintainers:
  - name: enzyme-health
    url: https://github.com/enzyme-health
keywords:
- job
- api
- primitives
